AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'test/**/*_test.rb'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*_test.rb'

Metrics/MethodLength:
  Max: 25

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
